FROM node:14-alpine as development

WORKDIR /usr/local/users-service

COPY package*.json tsconfig*.json ./

RUN npm install

COPY . ./

RUN npm run build

CMD ["npm", "run", "start:dev"]

FROM node:14-alpine as production

WORKDIR /usr/local/users-service

COPY package*.json tsconfig*.json ./

RUN npm install --prod

COPY --from=development /usr/local/users-service/dist ./dist

CMD ["npm", "run", "start"]